"""empty message

Revision ID: d3306e3415bf
Revises: 1ed087155a71
Create Date: 2023-02-24 19:05:27.006206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3306e3415bf'
down_revision = '1ed087155a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_patients',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mrn', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mrn'], ['patients.mrn'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'mrn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_patients')
    # ### end Alembic commands ###
