"""empty message

Revision ID: 1ed087155a71
Revises: f92312480fe7
Create Date: 2023-02-24 19:00:17.163556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed087155a71'
down_revision = 'f92312480fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('mrn', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pt_name', sa.String(length=128), nullable=False),
    sa.Column('pt_surname', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('mrn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients')
    # ### end Alembic commands ###
