"""empty message

Revision ID: fc7ae02e6b00
Revises: 154d8fd48099
Create Date: 2023-02-27 02:07:57.263267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc7ae02e6b00'
down_revision = '154d8fd48099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('dob', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'dob')
    # ### end Alembic commands ###
