"""empty message

Revision ID: 154d8fd48099
Revises: eb5b30ac2716
Create Date: 2023-02-27 01:57:57.619945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154d8fd48099'
down_revision = 'eb5b30ac2716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diagnosis', sa.String(length=128), nullable=False),
    sa.Column('symptoms', sa.String(length=128), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('patient_mrn', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_mrn'], ['patients.mrn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medication', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('dosage', sa.Text(), nullable=False),
    sa.Column('route', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Text(), nullable=False),
    sa.Column('patient_mrn', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_mrn'], ['patients.mrn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surgeries',
    sa.Column('surgery_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('procedure', sa.String(length=128), nullable=False),
    sa.Column('date_of_surgery', sa.Date(), nullable=True),
    sa.Column('patient_mrn', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_mrn'], ['patients.mrn'], ),
    sa.PrimaryKeyConstraint('surgery_id')
    )
    op.create_table('vital_signs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_taken', sa.TIMESTAMP(), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('systolic_bp', sa.Integer(), nullable=True),
    sa.Column('diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('temp_f', sa.Float(precision=1), nullable=True),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('respirations', sa.Integer(), nullable=True),
    sa.Column('patient_mrn', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_mrn'], ['patients.mrn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allergies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reaction', sa.Text(), nullable=False),
    sa.Column('anaphylaxis', sa.Boolean(), nullable=True),
    sa.Column('medications_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medications_id'], ['medications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allergies')
    op.drop_table('vital_signs')
    op.drop_table('surgeries')
    op.drop_table('medications')
    op.drop_table('medical_conditions')
    # ### end Alembic commands ###
