"""empty message

Revision ID: eb5b30ac2716
Revises: d3306e3415bf
Create Date: 2023-02-24 19:52:50.718853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5b30ac2716'
down_revision = 'd3306e3415bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_patients', sa.Column('patient_mrn', sa.Integer(), nullable=False))
    op.drop_constraint('users_patients_mrn_fkey', 'users_patients', type_='foreignkey')
    op.create_foreign_key(None, 'users_patients', 'patients', ['patient_mrn'], ['mrn'])
    op.drop_column('users_patients', 'mrn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_patients', sa.Column('mrn', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users_patients', type_='foreignkey')
    op.create_foreign_key('users_patients_mrn_fkey', 'users_patients', 'patients', ['mrn'], ['mrn'])
    op.drop_column('users_patients', 'patient_mrn')
    # ### end Alembic commands ###
